# 服务器配置
server:
  port: 8002  # 应用服务端口号，选择8002避免与其他常用服务冲突

# Spring框架相关配置
spring:
  application:
    name: short-link-admin  # 服务名称，用于服务注册与发现
  
  # 数据源配置
  datasource:
    # 使用ShardingSphere作为数据源驱动
    # 支持读写分离、分库分表等高级特性
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # 通过环境变量database.env控制加载不同环境的配置文件
    # 默认使用dev环境配置
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  
  # Redis配置
  data:
    redis:
      host: 127.0.0.1      # Redis服务器地址
      port: 6379           # Redis服务端口
      password: 123456     # Redis访问密码
  
  # Nacos服务发现配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # Nacos服务器地址和端口

# 短链接服务自定义配置
short-link:
  group:
    max-num: 20  # 单个用户最大分组数量限制
  
  # 流量控制配置
  flow-limit:
    enable: true              # 是否启用流量控制
    time-window: 1           # 限流时间窗口（单位：秒）
    max-access-count: 20     # 在时间窗口内允许的最大访问次数
